#  -- ==============================================   
#  --  proyecto: < 03-anylist >
#  --  seccion5: < Anylist - GraphQL + Postgres > < seccion 5>
#  --  filex:    sc_2\sc_Node8\2GraphQL\N10.04.graphQL-Postgres.sql
#  --  file :   docker-compose.yml
#  --  ==============================================  
version: '3'

services:
  db:
    image: postgres:14.4
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: anyListDB
    volumes:
      - ./postgres:/var/lib/postgresql/data

